import { create } from 'zustand';

const detectLanguage = () => {
  if (typeof window === 'undefined') return 'ru';
  const browserLang = navigator.language || navigator.userLanguage || 'ru';
  const shortLang = browserLang.substring(0, 2).toLowerCase();
  if (['ru', 'uz', 'en'].includes(shortLang)) {
    return shortLang;
  }
  return 'ru'; // Default to Russian since user is in Tashkent
};

export const translations = {
  en: {
    // Nav
    services: "Services",
    expertise: "Expertise",
    scale: "Scale",
    login: "Log In",
    logout: "Log Out",
    startProject: "Start Project",
    disconnect: "Disconnect",
    // Hero
    heroTitle: "The Best Web Studio in Uzbekistan.",
    heroTitleSub: "Making websites beautifully.",
    heroDesc: "We design, develop, and launch high-performance websites and mobile apps. We handle the engineering so you can grow.",
    heroStatsProjects: "Projects Launched",
    heroStatsUptime: "Uptime SLA",
    heroStatsUsers: "Active Users",
    // Services
    whatWeDo: "What We Do",
    engineeredStability: "Engineered for stability.",
    designedGrowth: "Designed for growth.",
    // Cards
    cardWebTitle: "Custom Web Development",
    cardWebDesc: "High-performance, secure, and SEO-optimized web systems built with modern frameworks (React, Next.js, Node.js) that load instantly.",
    cardAppTitle: "iOS & Android Apps",
    cardAppDesc: "Native & cross-platform applications crafted for optimal user experiences, from design to submission in the App Store and Google Play.",
    cardDesignTitle: "UI/UX Interface Design",
    cardDesignDesc: "Visual design systems that communicate brand trust. Pixel-perfect, accessible, and structured user flows that drive customer conversion.",
    cardCloudTitle: "Cloud Infrastructure",
    cardCloudDesc: "Reliable CI/CD pipelines, containerized orchestration (Docker/Kubernetes), and scalable architecture setups on AWS, GCP, and Vercel.",
    cardApiTitle: "Integrations & API Design",
    cardApiDesc: "Seamless connections to CRMs, payment gateways, ERP pipelines, and secure enterprise backend services.",
    cardSupportTitle: "Support & Optimization",
    cardSupportDesc: "Post-launch support, performance audits, page speed optimization, security updates, and database maintenance to keep apps healthy.",
    // Research
    researchAreas: "Research Areas",
    threePillars: "Three pillars",
    scientificExecution: "of scientific execution",
    pillar1Title: "High-Performance Web Engines",
    pillar1Desc: "Building sub-second loading web applications using edge-rendering, caching layers, and clean, modular component structures.",
    pillar2Title: "Fluid Native Mobile Frameworks",
    pillar2Desc: "Crafting mobile software that utilizes GPU hardware acceleration for smooth 120Hz animations, local databases, and offline accessibility.",
    pillar3Title: "Secure & Automated Cloud",
    pillar3Desc: "Deploying auto-scaling cloud clusters protected by firewalls, standard authorization models, and fully automated deployment workflows.",
    // Work
    selectedWork: "Selected Work",
    caseStudies: "Case studies",
    builtSolutions: "of solutions built",
    visitWebsite: "Visit Website",
    viewCase: "View Case Study",
    // Scale
    byNumbers: "By The Numbers",
    scaleSpeaks: "Scale that speaks",
    itself: "for itself",
    numCardProjects: "Web & mobile projects launched successfully",
    numCardUptime: "Uptime and build reliability standards",
    numCardEngineers: "Experienced engineers and product designers",
    numCardSpeed: "Average load speed improvement for clients",
    // CTA
    getInvolved: "Get Involved",
    nextBreakthrough: "The next breakthrough",
    startsYou: "starts with you",
    ctaDesc: "Have a website or mobile application concept? Let our team handle the engineering, design, and deployment. We launch products under iOS, Android, and Web platforms.",
    // Footer
    footerCopy: "Quality • Intelligence • Experience. All rights reserved.",
    // Sidebar & Forms
    establishIdentity: "Establish Identity",
    authSubtitle: "Create your developer profile and choose an avatar to authorize secure connections.",
    fullName: "Full Name",
    emailAddr: "Email Address",
    chooseAvatar: "Choose Avatar Identity",
    password: "Password",
    createAccount: "Create Account",
    newWorkspace: "New Workspace",
    workspaceSubtitle: "Outline the requirements and specify features for your sandbox project. Our AI will analyze your specifications and generate an estimate.",
    workspaceName: "Workspace Name",
    envEngine: "Environment Engine",
    projRequirements: "Project Requirements (AI Analysis)",
    analyzeReqs: "Analyze Requirements",
    neuralAssessment: "Neural Assessment",
    radarSubtitle: "Our neural interpreter is analyzing requirements and estimating resources.",
    aiCostBreakdown: "AI Cost Breakdown",
    aiSubtitle: "Based on your requirements, the AI has compiled the following invoice quote.",
    projectTarget: "Project Target",
    timeline: "Timeline",
    itemizedTasks: "Itemized Tasks",
    invoicedTotal: "Invoiced Total",
    proceedCheckout: "Proceed to Checkout",
    confirmPayment: "Confirm Payment",
    p2pSender: "Your card or phone number (Sender)",
    p2pReceipt: "Transaction ID / Receipt Code (Click / Payme)",
    workspaceActive: "Workspace Active!",
    receiptEmailed: "Transaction confirmed. A billing copy of your receipt has been dispatched to your e-mail.",
    amountPaid: "Amount Paid:",
    method: "Method:",
    status: "Status:",
    online: "Online",
    successFooter: "An email with details has been sent. We will verify the receipt ID and contact you within 15 minutes.",
    returnHome: "Return to Home",
    connectWorkspace: "Proceed to Workspace",
    connectingAuth: "Connecting to secure auth gateway...",
    creatingProfile: "Creating secure developer profile...",
    syncingAvatar: "Syncing custom avatar identity...",
    accessGranted: "Access Granted!",
    authorized: "Authorized",
    authPrompt: "You can now proceed to initialize your first project workspace."
  },
  ru: {
    // Nav
    services: "Услуги",
    expertise: "Экспертиза",
    scale: "Масштаб",
    login: "Войти",
    logout: "Выйти",
    startProject: "Начать проект",
    disconnect: "Выйти",
    // Hero
    heroTitle: "Лучшая веб-студия в Узбекистане.",
    heroTitleSub: "Делаем сайты красиво.",
    heroDesc: "Проектируем, разрабатываем и запускаем быстрые сайты и мобильные приложения. Берем на себя инженерию, чтобы вы могли расти.",
    heroStatsProjects: "Проектов запущено",
    heroStatsUptime: "Время работы SLA",
    heroStatsUsers: "Пользователей",
    // Services
    whatWeDo: "Что мы делаем",
    engineeredStability: "Разработано для стабильности.",
    designedGrowth: "Создано для роста.",
    // Cards
    cardWebTitle: "Разработка сайтов",
    cardWebDesc: "Высокопроизводительные, безопасные и SEO-оптимизированные веб-системы на современных фреймворках (React, Next.js, Node.js) с мгновенной загрузкой.",
    cardAppTitle: "Приложения iOS & Android",
    cardAppDesc: "Нативные и кроссплатформенные мобильные приложения с упором на UX, от дизайна до публикации в App Store и Google Play.",
    cardDesignTitle: "UI/UX Дизайн интерфейсов",
    cardDesignDesc: "Визуальные дизайн-системы, вызывающие доверие к бренду. Пиксельно-точные, доступные и конвертирующие пользовательские интерфейсы.",
    cardCloudTitle: "Облачная инфраструктура",
    cardCloudDesc: "Надежные CI/CD пайплайны, контейнеризация (Docker/Kubernetes) и масштабируемая архитектура на AWS, GCP и Vercel.",
    cardApiTitle: "Интеграции и API",
    cardApiDesc: "Бесшовное подключение CRM-систем, платежных шлюзов, ERP-каналов и защищенных корпоративных бэкенд-сервисов.",
    cardSupportTitle: "Поддержка и оптимизация",
    cardSupportDesc: "Послепусковая поддержка, аудит производительности, оптимизация скорости, обновления безопасности и обслуживание баз данных.",
    // Research
    researchAreas: "Направления",
    threePillars: "Три столпа",
    scientificExecution: "научного исполнения",
    pillar1Title: "Высокопроизводительные веб-движки",
    pillar1Desc: "Создание веб-приложений с субсекундной загрузкой с использованием рендеринга на границе сети, слоев кэширования и чистой модульной архитектуры.",
    pillar2Title: "Адаптивные мобильные фреймворки",
    pillar2Desc: "Разработка мобильного ПО с аппаратным ускорением GPU для плавных анимаций 120 Гц, локальными БД и оффлайн-доступом.",
    pillar3Title: "Безопасное и автоматизированное облако",
    pillar3Desc: "Развертывание облачных кластеров с автоматическим масштабированием, защищенных файрволами, стандартными моделями авторизации и CI/CD.",
    // Work
    selectedWork: "Портфолио",
    caseStudies: "Кейсы решений",
    builtSolutions: "готовых к запуску",
    visitWebsite: "Перейти на сайт",
    viewCase: "Смотреть кейс",
    // Scale
    byNumbers: "В цифрах",
    scaleSpeaks: "Масштаб, который говорит",
    itself: "сам за себя",
    numCardProjects: "Успешно запущенных веб- и мобильных проектов",
    numCardUptime: "Стандарты надежности аптайма и сборок",
    numCardEngineers: "Опытных инженеров и дизайнеров продуктов",
    numCardSpeed: "Среднее ускорение загрузки сайтов клиентов",
    // CTA
    getInvolved: "Сотрудничество",
    nextBreakthrough: "Следующий прорыв",
    startsYou: "начинается с вас",
    ctaDesc: "Есть идея сайта или мобильного приложения? Наша команда возьмет на себя проектирование, дизайн и деплой на iOS, Android и Web.",
    // Footer
    footerCopy: "Качество • Интеллект • Опыт. Все права защищены.",
    // Sidebar & Forms
    establishIdentity: "Создать профиль",
    authSubtitle: "Создайте профиль разработчика и выберите аватар для авторизации безопасного соединения.",
    fullName: "Полное имя",
    emailAddr: "Электронная почта",
    chooseAvatar: "Выберите аватар",
    password: "Пароль",
    createAccount: "Создать аккаунт",
    newWorkspace: "Новая рабочая область",
    workspaceSubtitle: "Опишите ваши требования и укажите функции песочницы. Наш ИИ проанализирует параметры и рассчитает смету.",
    workspaceName: "Имя рабочей области",
    envEngine: "Движок окружения",
    projRequirements: "Требования к проекту (AI-анализ)",
    analyzeReqs: "Анализировать требования",
    neuralAssessment: "Нейросетевой анализ",
    radarSubtitle: "Наш нейросетевой анализатор изучает требования и оценивает ресурсы.",
    aiCostBreakdown: "Смета от ИИ",
    aiSubtitle: "На основе ваших требований ИИ сформировал следующий счет-смету.",
    projectTarget: "Цель проекта",
    timeline: "Сроки выполнения",
    itemizedTasks: "Задачи сметы",
    invoicedTotal: "Итого к оплате",
    proceedCheckout: "Перейти к оплате",
    confirmPayment: "Подтвердить оплату",
    p2pSender: "Ваша карта или телефон (Отправитель)",
    p2pReceipt: "ID транзакции / Код чека (Click / Payme)",
    workspaceActive: "Песочница создана!",
    receiptEmailed: "Транзакция подтверждена. Электронный чек отправлен на ваш e-mail.",
    amountPaid: "Сумма перевода:",
    method: "Метод:",
    status: "Статус:",
    online: "Активен",
    successFooter: "Детали зачисления отправлены на почту. Мы проверим ID чека и свяжемся с вами в течение 15 минут.",
    returnHome: "Вернуться на главную",
    connectWorkspace: "Перейти к песочнице",
    connectingAuth: "Подключение к шлюзу авторизации...",
    creatingProfile: "Создание безопасного профиля...",
    syncingAvatar: "Синхронизация аватара...",
    accessGranted: "Доступ разрешен!",
    authorized: "Авторизован",
    authPrompt: "Теперь вы можете перейти к созданию своей первой рабочей области."
  },
  uz: {
    // Nav
    services: "Xizmatlar",
    expertise: "Ekspertiza",
    scale: "Miqyos",
    login: "Kirish",
    logout: "Chiqish",
    startProject: "Loyihani boshlash",
    disconnect: "Chiqish",
    // Hero
    heroTitle: "O'zbekistondagi eng yaxshi veb-studiya.",
    heroTitleSub: "Saytlarni chiroyli qilamiz.",
    heroDesc: "Tezkor veb-saytlar va mobil ilovalarni loyihalashtiramiz, ishlab chiqamiz va ishga tushiramiz. Biz texnologiyalarni o'z zimmamizga olamiz, toki siz o'sa olasiz.",
    heroStatsProjects: "Loyihalar ishga tushirilgan",
    heroStatsUptime: "SLA Uptime vaqti",
    heroStatsUsers: "Foydalanuvchilar",
    // Services
    whatWeDo: "Biz nima qilamiz",
    engineeredStability: "Barqarorlik uchun mo'ljallangan.",
    designedGrowth: "O'sish uchun yaratilgan.",
    // Cards
    cardWebTitle: "Veb-saytlar yaratish",
    cardWebDesc: "Zamonaviy freymvorklarda (React, Next.js, Node.js) yaratilgan, tez yuklanadigan, xavfsiz va SEO-optimallashtirilgan veb-tizimlar.",
    cardAppTitle: "iOS va Android ilovalar",
    cardAppDesc: "UX-ga yo'naltirilgan, dizayndan tortib App Store va Google Play-da chop etishgacha bo'lgan nativ va krossplatformali mobil ilovalar.",
    cardDesignTitle: "UI/UX Interface dizayni",
    cardDesignDesc: "Brendga ishonch uyg'otadigan vizual dizayn tizimlari. Piksel darajasida aniq, qulay va mijozlarni jalb etuvchi interfeyslar.",
    cardCloudTitle: "Bulutli infratuzilma",
    cardCloudDesc: "AWS, GCP va Vercel platformalarida ishonchli CI/CD quvurlari, konteynerlashtirish (Docker/Kubernetes) va kengayuvchi arxitektura.",
    cardApiTitle: "Integratsiyalar va API",
    cardApiDesc: "CRM tizimlar, to'lov shlyuzlari, ERP kanallari va xavfsiz korporativ backend xizmatlarini uzluksiz ulash.",
    cardSupportTitle: "Qo'llab-quvvatlash va optimallashtirish",
    cardSupportDesc: "Ishga tushirilgandan keyingi yordam, samaradorlik auditi, tezlikni optimallashtirish, xavfsizlik yangilanishlari va MB xizmati.",
    // Research
    researchAreas: "Tadqiqot yo'nalishlari",
    threePillars: "Uchta ustun",
    scientificExecution: "ilmiy bajarilish",
    pillar1Title: "Yuqori samarali veb-dvigatellar",
    pillar1Desc: "Edge rendering, kesh qatlamlari va toza modulli arxitektura yordamida soniyadan kam vaqtda yuklanadigan veb-ilovalar yaratish.",
    pillar2Title: "Moslashuvchan mobil freymvorklar",
    pillar2Desc: "Silliq 120Hz animatsiyalar, lokal MB va oflayn rejim uchun GPU apparat tezlashuvidan foydalanadigan mobil dasturlar yaratish.",
    pillar3Title: "Xavfsiz va avtomatlashtirilgan bulut",
    pillar3Desc: "Tarmoq ekranlari, standart avtorizatsiya va to'liq avtomatlashtirilgan CI/CD bilan himoyalangan avtomatik kengayuvchi bulut klasterlari.",
    // Work
    selectedWork: "Tanlangan ishlar",
    caseStudies: "Tayyor yechimlar",
    builtSolutions: "keyslari",
    visitWebsite: "Saytga o'tish",
    viewCase: "Keysni ko'rish",
    // Scale
    byNumbers: "Raqamlarda",
    scaleSpeaks: "O'z-o'zidan gapiradigan",
    itself: "miqyos",
    numCardProjects: "Muvaffaqiyatli ishga tushirilgan veb va mobil loyihalar",
    numCardUptime: "Uptime va yig'ishning ishonchlilik standartlari",
    numCardEngineers: "Tajribali muhandislar va mahsulot dizaynerlari",
    numCardSpeed: "Mijozlar saytlari yuklanishining o'rtacha tezlashishi",
    // CTA
    getInvolved: "Hamkorlik",
    nextBreakthrough: "Keyingi yutuq",
    startsYou: "sizdan boshlanadi",
    ctaDesc: "Sayt yoki mobil ilova g'oyangiz bormi? Jamoamiz loyihalash, dizayn va iOS, Android hamda Web platformalarida ishga tushirishni o'z zimmasiga oladi.",
    // Footer
    footerCopy: "Sifat • Intellekt • Tajriba. Barcha huquqlar himoyalangan.",
    // Sidebar & Forms
    establishIdentity: "Shaxsni tasdiqlash",
    authSubtitle: "Xavfsiz ulanishni avtorizatsiya qilish uchun ishlab chiquvchi profilini yarating va avatar tanlang.",
    fullName: "To'liq ism",
    emailAddr: "Elektron pochta",
    chooseAvatar: "Avatar tanlang",
    password: "Parol",
    createAccount: "Hisob yaratish",
    newWorkspace: "Yangi ish maydoni",
    workspaceSubtitle: "Loyiha talablarini tavsiflang va parametrlarini ko'rsating. Bizning Sun'iy intellekt smetani hisoblab beradi.",
    workspaceName: "Ish maydoni nomi",
    envEngine: "Atrof-muhit dvigateli",
    projRequirements: "Loyiha talablari (AI-tahlil)",
    analyzeReqs: "Talablarni tahlil qilish",
    neuralAssessment: "Neyrotahlil",
    radarSubtitle: "Bizning neyrotahlil tizimimiz talablarni o'rganib chiqib, resurslarni baholamoqda.",
    aiCostBreakdown: "AI smetasi",
    aiSubtitle: "Sizning talablaringiz asosida Sun'iy intellekt quyidagi hisob-smetani shakllantirdi.",
    projectTarget: "Loyiha maqsadi",
    timeline: "Bajarilish muddati",
    itemizedTasks: "Smeta vazifalari",
    invoicedTotal: "Jami to'lov",
    proceedCheckout: "To'lovga o'tish",
    confirmPayment: "To'lovni tasdiqlash",
    p2pSender: "Koyangiz yoki telefon raqamingiz (Yuboruvchi)",
    p2pReceipt: "Tranzaksiya ID / Chek kodi (Click / Payme)",
    workspaceActive: "Ish maydoni yaratildi!",
    receiptEmailed: "Tranzaksiya tasdiqlandi. Elektron chek emailingizga yuborildi.",
    amountPaid: "To'lov summasi:",
    method: "Uslub:",
    status: "Holat:",
    online: "Faol",
    successFooter: "To'lov tafsilotlari yuborildi. Biz chek ID-sini tekshirib, 15 daqiqa ichida siz bilan bog'lanamiz.",
    returnHome: "Bosh sahifaga qaytish",
    connectWorkspace: "Ish maydoniga o'tish",
    connectingAuth: "Avtorizatsiya shlyuziga ulanish...",
    creatingProfile: "Xavfsiz profil yaratish...",
    syncingAvatar: "Avatarni sinxronlashtirish...",
    accessGranted: "Ruxsat berildi!",
    authorized: "Avtorizatsiyadan o'tdi",
    authPrompt: "Endi siz birinchi ish maydoningizni yaratishga o'tishingiz mumkin."
  }
};

export const useLangStore = create((set) => ({
  lang: detectLanguage(),
  setLang: (newLang) => set({ lang: newLang }),
}));
